### ISSUE TITLE
No "configure" file

### ISSUE THREAD

**Issue by fran3434** [NationalAssociationOfRealtors/ezRETS#1]
I'm attempting to follow the directions in ezRETS/doc/build/unix.txt , but there doesn't seem to be a file called "configure" .

**Comment by ktgeek** [comment]
Part of our learning curve into moving to github and its auto generation of tarballs.  Make sure you have autoconf installed, cd into the ezrets source directory and type "autoconf"  That should generate the configure script for you.

Keith

On Jan 12, 2015, at 4:38 PM, Francis Gravel <notifications@github.com<mailto:notifications@github.com>> wrote:

I'm attempting to follow the directions in ezRETS/doc/build/unix.txt , but there doesn't seem to be a file called "configure" .

—
Reply to this email directly or view it on GitHubhttps://github.com/NationalAssociationOfRealtors/ezRETS/issues/1.

## 

Keith T. Garner - kgarner@realtors.orgmailto:kgarner@realtors.org - 312-329-3294 - http://realtor.org/
National Association of REALTORS® - VP - Information Technology Services

**Comment by fran3434** [comment]
Yes indeed. 
Thanks,
Francis
